import React from "react";
import Header from "../../components/Profile/Header";
import Head from "next/head";

export default function Quiz({ session }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex flex-auto">
        PPPP
      </main>
      <footer></footer>
    </div>
  );
}
