import React, { useState } from "react";
import Header from "../../components/Profile/Header";
import Head from "next/head";
import QuizGenerator from "../../components/Quizz/QuizGenerator";
import QuizSelector from "../../components/Quizz/QuizSelector";
import { getSession } from "next-auth/react";
import Login from "../../components/Login";

export default function Quiz({ session }) {
  if (!session) return <Login />;
  const [createQuiz, setCreateQuiz] = useState(true);
  return (
    <div className="h-screen overflow-auto bg-gradient-to-tr from-[#088DE5] to-[#47D7CE] via-[#4897BD]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header props={{ quiz: true, profile: false, ranking: false }} />
      <main>
        <div className="flex flex-row justify-center py-2 space-x-4 bg-transparent">
          <p
            className={`font-mono text-xl px-2 py-2 text-white border-b-2 ${
              createQuiz ? "border-[#b2301c]" : "border-transparent"
            } cursor-pointer shadow-lg rounded-md`}
            onClick={() => setCreateQuiz(true)}
          >
            New Quiz
          </p>
          <p
            className={`font-mono text-xl px-2 py-2 text-white border-b-2 ${
              !createQuiz ? "border-[#b2301c]" : "border-transparent"
            } cursor-pointer shadow-lg rounded-md`}
            onClick={() => setCreateQuiz(false)}
          >
            Take a Quiz
          </p>
        </div>
        {createQuiz && <QuizGenerator />}
        {!createQuiz && <QuizSelector />}
      </main>
      <footer></footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: { session },
  };
}
