import Head from "next/head";
import Header from "../components/Profile/Header";
import Profile from "../components/Profile/Profile";
import Portofolio from "../components/Profile/Portofolio";
import { getSession } from "next-auth/react";
import Login from "../components/Login";

export default function Home({session}) {
  if (!session) return <Login />;
  return (
    <div className=" h-screen overflow-auto bg-gradient-to-bl to-[#5FFBF1] from-[#C792B0] via-[#86A8E7]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header props={{ quiz: false, profile: true, ranking: false }} />
      <main className={"flex flex-col"}>
        <Profile />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: { session },
  };
}
