import Head from "next/head";
import Header from "../components/Profile/Header";
import Profile from "../components/Profile/Profile";
import Portofolio from "../components/Profile/Portofolio";

export default function Home() {
  return (
    <div className=" h-screen bg-gradient-to-bl to-[#5FFBF1] from-[#C792B0] via-[#86A8E7]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={"flex flex-col"}>
        <Profile />
        <Portofolio />
      </main>
    </div>
  );
}
